"""Build ic_priorities.csv from curated extracts of each plan.

Priorities are extracted from a structured manual curation guided by the
PDF text reads in plan_pages.json. Each row carries:
  ic, plan_year, priority_id, priority_name, priority_description,
  source_quote, source_page, aou_theme_tags (;-separated), aou_focus_area_tags
"""
import csv
import os

OUT = "/Users/melissahaendel/Documents/GitHub/all-of-us/resources/aou-ic-alignment/ic_priorities.csv"

# Header column list
COLS = [
    "ic",
    "plan_year",
    "priority_id",
    "priority_name",
    "priority_description",
    "source_quote",
    "source_page",
    "aou_theme_tags",
    "aou_focus_area_tags",
]

# AoU 19-theme codes (string ids)
# 1 Cardiometabolic; 2 Genomics; 3 Methods/Infra; 4 MH/SU; 5 Cancer; 6 SDOH;
# 7 Wearables; 8 Infectious; 9 Autoimmune; 10 Rare; 11 Aging/ADRD;
# 12 Dermatology; 13 Resp/Sleep; 14 Neuro non-ADRD; 15 Pregnancy/Women;
# 16 Pharmacogenomics; 17 ELSI; 18 Ophth/ENT; 19 Environmental
#
# AoU 8 Focus Areas:
# FA1 Prevalent Common & Rare; FA2 Maternal/Child; FA3 Healthy Aging;
# FA4 Return of Results; FA5 Lifestyle/Substance/Behavioral; FA6 Environment;
# FA7 Health Equity; FA8 Genetics & Biology

ROWS = [
    # =================================================================
    # NIH-WIDE (FY2021-2025) — 3 Objectives + 5 Crosscutting Themes
    # =================================================================
    ("NIH-Wide", "2021-2025", "NIHW-OBJ1-A", "Driving Foundational Science",
     "Advance basic, translational, clinical, and population-based science across biology and behavior, including building data resources and tools.",
     "Objective 1: Advancing Biomedical and Behavioral Sciences ... Driving Foundational Science ... Building Data Resources to Enable Research Progress",
     "p.iii–iv", "2;3", "FA8"),
    ("NIH-Wide", "2021-2025", "NIHW-OBJ1-B", "Preventing Disease and Promoting Health",
     "Prevent disease and promote health through population-based science, behavioral/social determinants research, and lifestyle interventions.",
     "Preventing Disease and Promoting Health ... Understanding Biological, Behavioral, and Social Determinants of Population Health",
     "p.iii", "1;4;6", "FA1;FA5;FA7"),
    ("NIH-Wide", "2021-2025", "NIHW-OBJ1-C", "Advancing Treatments and Cures",
     "Catalyze translation of discoveries into treatments and cures via partnerships with industry, patients, and other stakeholders.",
     "Partnering to Advance Treatments and Cures",
     "p.iii–iv", "5;10;16", "FA1;FA4"),
    ("NIH-Wide", "2021-2025", "NIHW-OBJ2-A", "Enhancing Workforce",
     "Develop and maintain a diverse biomedical and behavioral research workforce.",
     "Enhancing the Biomedical and Behavioral Research Workforce",
     "p.iv", "3;17", "FA4"),
    ("NIH-Wide", "2021-2025", "NIHW-OBJ2-B", "Supporting Research Resources and Infrastructure",
     "Sustain shared infrastructure including data resources, cohorts, and informatics, supporting research at scale.",
     "Supporting Research Resources and Infrastructure",
     "p.iv", "3;17", "FA8"),
    ("NIH-Wide", "2021-2025", "NIHW-OBJ3", "Scientific Integrity, Stewardship & Social Responsibility",
     "Promote highest level of scientific integrity, public accountability, and social responsibility in conduct of science.",
     "Objective 3: Exemplifying and Promoting the Highest Level of Scientific Integrity, Public Accountability, and Social Responsibility in the Conduct of Science",
     "p.iv", "17", "FA4"),
    ("NIH-Wide", "2021-2025", "NIHW-CCT1", "Improving Minority Health & Reducing Health Disparities",
     "Pan-NIH crosscutting theme: address structural inequities and improve minority health.",
     "five key Crosscutting Themes that span all aspects of NIH's Strategy ... Improving Minority Health and Reducing Health Disparities",
     "p.vii (xi); p.32", "6;12;18", "FA7"),
    ("NIH-Wide", "2021-2025", "NIHW-CCT2", "Enhancing Women's Health",
     "Pan-NIH crosscutting theme: women's health beyond reproductive health to address conditions affecting women differently.",
     "Enhancing Women's Health",
     "p.vii;p.33", "15;6", "FA2;FA7"),
    ("NIH-Wide", "2021-2025", "NIHW-CCT3", "Addressing Public Health Challenges Across the Lifespan",
     "Pan-NIH crosscutting theme: lifespan health, with attention to maternal, child, adolescent, adult, and older-adult priorities.",
     "Addressing Public Health Challenges Across the Lifespan",
     "p.vii;p.33", "11;15", "FA1;FA2;FA3"),
    ("NIH-Wide", "2021-2025", "NIHW-CCT4", "Promoting Collaborative Science",
     "Pan-NIH crosscutting theme: team science and trans-NIH collaboration.",
     "Promoting Collaborative Science",
     "p.vii;p.34", "3", "FA8"),
    ("NIH-Wide", "2021-2025", "NIHW-CCT5", "Leveraging Data Science for Biomedical Discovery",
     "Pan-NIH crosscutting theme: data science and AI/ML enablement across the agency.",
     "Leveraging Data Science for Biomedical Discovery",
     "p.vii;p.34", "3;2", "FA8"),

    # =================================================================
    # NCI National Cancer Plan — 8 Goals (Biden Cancer Moonshot framework)
    # =================================================================
    ("NCI", "NationalCancerPlan-2023", "NCP-G1", "Prevent Cancer",
     "All people and society adopt proven strategies that reduce the risk of cancer.",
     "1. Prevent Cancer — All people and society adopt proven strategies that reduce the risk of cancer.",
     "p.5", "5", "FA1"),
    ("NCI", "NationalCancerPlan-2023", "NCP-G2", "Detect Cancers Early",
     "Cancers are detected and treated at early stages, enabling more effective treatment and reducing mortality.",
     "2. Detect Cancers Early — Cancers are detected and treated at early stages, enabling more effective treatment and reducing morbidity and mortality.",
     "p.5", "5", "FA1"),
    ("NCI", "NationalCancerPlan-2023", "NCP-G3", "Develop Effective Treatments",
     "Effective treatment, with minimal side effects, is accessible to all people including rare and metastatic cancers.",
     "3. Develop Effective Treatments — Effective treatment, with minimal side effects, is accessible to all people with all cancers, including those with rare cancers",
     "p.5", "5;16", "FA1;FA4"),
    ("NCI", "NationalCancerPlan-2023", "NCP-G4", "Eliminate Inequities",
     "Disparities in cancer risk, incidence, treatment, and mortality are eliminated through equitable access.",
     "4. Eliminate Inequities — Disparities in cancer risk factors, incidence, treatment side effects, and mortality are eliminated",
     "p.5", "5;6", "FA1;FA7"),
    ("NCI", "NationalCancerPlan-2023", "NCP-G5", "Deliver Optimal Care",
     "Health care system delivers evidence-based, patient-centered care prioritizing prevention and survivorship.",
     "5. Deliver Optimal Care — The health care system delivers to all people evidence-based, patient-centered care",
     "p.5", "5", "FA1"),
    ("NCI", "NationalCancerPlan-2023", "NCP-G6", "Engage Every Person",
     "Every person with cancer or at risk has opportunity to participate in research; barriers eliminated.",
     "6. Engage Every Person — Every person with cancer or at risk for cancer has an opportunity to participate in research or otherwise contribute to the collective knowledge base",
     "p.5", "5;6;17", "FA1;FA4;FA7"),
    ("NCI", "NationalCancerPlan-2023", "NCP-G7", "Maximize Data Utility",
     "Secure sharing of privacy-protected health data is standard practice across research.",
     "7. Maximize Data Utility — Secure sharing of privacy-protected health data is standard practice throughout research",
     "p.5", "3;17", "FA8"),
    ("NCI", "NationalCancerPlan-2023", "NCP-G8", "Optimize the Workforce",
     "Cancer care and research workforce is diverse, reflects communities served, meets needs of all people.",
     "8. Optimize the Workforce — The cancer care and research workforce is diverse, reflects the communities served",
     "p.5", "5;6", "FA7"),

    # =================================================================
    # NCI Annual Plan & Budget FY2026 — funding priorities
    # =================================================================
    ("NCI", "AnnualPlanBudget-FY2026", "NCIB-WORKFORCE", "Strengthening the future cancer workforce",
     "Support training pipeline (K99/R00, ESI payline) and emerging data-science / public-health skills.",
     "NCI needs new programs to prepare a workforce skilled in data science, public health, and other fields that support cancer research",
     "p.4–5", "5;3", "FA8"),
    ("NCI", "AnnualPlanBudget-FY2026", "NCIB-MODERNIZE", "Modernizing cancer clinical studies",
     "Modernize clinical research with accessible, inclusive, nimble studies including the Cancer Screening Research Network (CSRN, multi-cancer detection).",
     "Clinical studies are a key step ... NCI launched the Cancer Screening Research Network ... evaluate these tests",
     "p.5–6", "5", "FA1"),
    ("NCI", "AnnualPlanBudget-FY2026", "NCIB-CHILDHOOD", "Childhood Cancer Data Initiative",
     "Dedicated $50M for CCDI to expand pediatric cancer data infrastructure.",
     "This proposal includes $50 million for the 7th year of the Childhood Cancer Data Initiative",
     "p.4", "5;15;10", "FA1;FA2"),
    ("NCI", "AnnualPlanBudget-FY2026", "NCIB-AI", "AI for screening and precision oncology",
     "Leverage AI to predict treatments, enhance precancer screening, and detect hardest-to-detect cancers.",
     "NCI research is also illuminating artificial intelligence's (AI) potential to tell us which treatments are most likely to work, enhance screening",
     "p.3", "5;3", "FA8"),
    ("NCI", "AnnualPlanBudget-FY2026", "NCIB-FOUNDATION", "Sustained foundational cancer biology research",
     "Continue to support basic cancer biology as upstream input for prevention, detection, treatment.",
     "Virtually every new cancer diagnostic, therapeutic, or preventive measure begins with addressing a basic science research question",
     "p.7", "5;2", "FA8"),
    ("NCI", "AnnualPlanBudget-FY2026", "NCIB-ACCESS", "Reach populations disproportionately affected",
     "Empower the workforce to reach people affected disproportionately and address access barriers to care.",
     "reach people affected disproportionately by cancer by addressing access to research and barriers to care",
     "p.3", "5;6", "FA1;FA7"),

    # =================================================================
    # NHGRI Strategic Vision 2020 (Nature, "Forefront of Genomics")
    # 4-area framework + 10 Bold Predictions
    # =================================================================
    ("NHGRI", "2020", "NHGRI-A1", "Robust foundation for genomics",
     "Build/maintain genomics tools, technologies, datasets, and resources for the entire biomedical community.",
     "Robust foundation for genomics ... reaffirm, sharpen, and even extend these tenets",
     "p.685 (PDF p.3)", "2;3", "FA8"),
    ("NHGRI", "2020", "NHGRI-A2", "Breaking down barriers",
     "Eliminate barriers between research and clinical care, between fields, and between participants and benefits.",
     "Breaking down barriers ... Sharp barriers between research and clinical care obstruct the virtuous cycle",
     "p.685", "2;3;17", "FA4"),
    ("NHGRI", "2020", "NHGRI-A3", "Compelling genomics research projects",
     "Drive ambitious flagship projects that advance the science of genomics including non-coding variation, multi-ancestry inclusion, and clinical implementation.",
     "Compelling genomics research projects",
     "p.685", "2;10;16", "FA8"),
    ("NHGRI", "2020", "NHGRI-A4", "Guiding principles & values (incl. ELSI)",
     "Foreground genomic ethical/legal/social implications research, ancestry inclusivity, and societal stewardship.",
     "Principles and values for human genomics ... informed by ... ELSI research",
     "p.685", "17;2;6", "FA4;FA7"),
    ("NHGRI", "2020", "NHGRI-BP4", "Move beyond race-based population descriptors",
     "Bold prediction: 'Research in human genomics will have moved beyond population descriptors based on historic social constructs such as race.'",
     "Research in human genomics will have moved beyond population descriptors based on historic social constructs such as race",
     "p.690 (PDF p.9)", "2;6", "FA7;FA8"),
    ("NHGRI", "2020", "NHGRI-BP6", "Make genomic information routine in clinical care",
     "Bold prediction: 'genomic information will have transitioned from boutique to mainstream in all clinical settings'.",
     "regular use of genomic information will have transitioned from boutique to mainstream in all clinical settings, making genomic testing as routine as complete blood counts",
     "p.690", "2;10;16", "FA1;FA4"),
    ("NHGRI", "2020", "NHGRI-BP7", "Eliminate variants of uncertain significance",
     "Bold prediction: 'the clinical relevance of all encountered genomic variants will be readily predictable, rendering VUS obsolete.'",
     "clinical relevance of all encountered genomic variants will be readily predictable, rendering the diagnostic designation 'variant of uncertain significance (VUS)' obsolete",
     "p.690", "10;2", "FA4"),
    ("NHGRI", "2020", "NHGRI-BP9", "Equitable benefit from genomics for ancestrally diverse populations",
     "Bold prediction: 'Individuals from ancestrally diverse backgrounds will benefit equitably from advances in human genomics.'",
     "Individuals from ancestrally diverse backgrounds will benefit equitably from advances in human genomics",
     "p.690", "2;6", "FA7;FA8"),
    ("NHGRI", "2020", "NHGRI-BP10", "Curative genomic therapies for genetic diseases",
     "Bold prediction: 'Breakthrough discoveries will lead to curative therapies involving genomic modifications for dozens of genetic diseases.'",
     "Breakthrough discoveries will lead to curative therapies involving genomic modifications for dozens of genetic diseases",
     "p.690", "10;16", "FA1;FA4"),
    ("NHGRI", "2020", "NHGRI-BP2", "Functional annotation of every human gene",
     "Bold prediction: 'The biological function(s) of every human gene will be known.'",
     "The biological function(s) of every human gene will be known; for non-coding elements ... such knowledge will be the rule",
     "p.690", "2", "FA8"),

    # =================================================================
    # NHLBI Strategic Vision FY2026-2030 — 8 Objectives + 5 Crosscutting
    # =================================================================
    ("NHLBI", "FY2026-2030", "NHLBI-O1", "Understand normal biological function and resilience",
     "Foundational research on healthy heart/lung/blood/sleep biology and resilience mechanisms.",
     "Understand normal biological function and resilience",
     "p.24", "1;13", "FA8"),
    ("NHLBI", "FY2026-2030", "NHLBI-O2", "Investigate pathobiological mechanisms of HLBS disease",
     "Investigate newly discovered pathobiological mechanisms important to onset and progression of heart, lung, and blood diseases and sleep disorders.",
     "Investigate newly discovered pathobiological mechanisms important to the onset and progression of heart, lung, and blood diseases and sleep disorders",
     "p.24", "1;13;2", "FA1;FA8"),
    ("NHLBI", "FY2026-2030", "NHLBI-O3", "Differences in health status among populations",
     "Investigate factors that account for differences in health status among populations.",
     "Investigate factors that account for differences in health status among populations",
     "p.24", "1;13;6", "FA7"),
    ("NHLBI", "FY2026-2030", "NHLBI-O4", "Individual differences in pathobiology and treatment response",
     "Identify factors that account for individual differences in pathobiology and responses to treatments.",
     "Identify factors that account for individual differences in pathobiology and in responses to treatments",
     "p.24", "1;13;2;16", "FA8"),
    ("NHLBI", "FY2026-2030", "NHLBI-O5", "Novel diagnostic and therapeutic strategies",
     "Develop and optimize novel diagnostic and therapeutic strategies to prevent, treat, and cure HLBS diseases.",
     "Develop and optimize novel diagnostic and therapeutic strategies to prevent, treat, and cure heart, lung, and blood diseases and sleep disorders",
     "p.24", "1;13", "FA1"),
    ("NHLBI", "FY2026-2030", "NHLBI-O6", "Clinical and implementation research",
     "Optimize clinical and implementation research to improve health and reduce disease.",
     "Optimize clinical and implementation research to improve health and reduce disease",
     "p.24", "1;13;3", "FA1"),
    ("NHLBI", "FY2026-2030", "NHLBI-O7", "Data science frontiers in HLBS",
     "Leverage emerging opportunities in data science to open new frontiers in HLBS research.",
     "Leverage emerging opportunities in data science to open new frontiers in research on heart, lung, and blood diseases and sleep disorders",
     "p.24", "3;2;7", "FA8"),
    ("NHLBI", "FY2026-2030", "NHLBI-O8", "Workforce for HLBS science",
     "Develop and sustain a scientific workforce capable of accomplishing the NHLBI's mission.",
     "Further develop and sustain a scientific workforce capable of accomplishing the NHLBI's mission",
     "p.24", "3", "FA8"),
    ("NHLBI", "FY2026-2030", "NHLBI-CCT-DS", "Crosscutting: Data Science",
     "Data science crosscuts all eight objectives — foundation models, multi-omics, AI/ML on HLBS data.",
     "five crosscutting themes ... address data science, health disparities, lifestyle behaviors, community and patient engaged research, and women's health",
     "p.24", "3;2", "FA8"),
    ("NHLBI", "FY2026-2030", "NHLBI-CCT-HD", "Crosscutting: Health Disparities",
     "Health disparities crosscut all eight objectives.",
     "five crosscutting themes ... health disparities",
     "p.24", "6", "FA7"),
    ("NHLBI", "FY2026-2030", "NHLBI-CCT-LIFE", "Crosscutting: Lifestyle Behaviors",
     "Lifestyle behaviors (physical activity, smoking, diet, sleep) crosscut HLBS science.",
     "five crosscutting themes ... lifestyle behaviors",
     "p.24", "1;4;7;13", "FA5"),
    ("NHLBI", "FY2026-2030", "NHLBI-CCT-CE", "Crosscutting: Community & Patient-Engaged Research",
     "Community and patient-engaged research crosscut HLBS objectives.",
     "five crosscutting themes ... community and patient engaged research",
     "p.24", "17;6", "FA4;FA7"),
    ("NHLBI", "FY2026-2030", "NHLBI-CCT-WH", "Crosscutting: Women's Health",
     "Women's health crosscuts all eight objectives.",
     "five crosscutting themes ... women's health",
     "p.24", "15;1", "FA2"),

    # =================================================================
    # NLM Strategic Plan 2017-2027 — 3 Goals × 4 Objectives
    # =================================================================
    ("NLM", "2017-2027", "NLM-G1-O1", "Connect resources of a digital research enterprise",
     "Collect/curate/integrate digital research objects with FAIR principles across literature and data.",
     "Objective 1.1: Connect the resources of a digital research enterprise ... FAIR principles",
     "p.9", "3", "FA8"),
    ("NLM", "2017-2027", "NLM-G1-O2", "Advance research in biomedical informatics and data science",
     "Drive R&D in informatics: curation at scale, analytics, visualization, modeling, NLP.",
     "Objective 1.2: Advance research ... curation, analytics, visualization, modeling, knowledge generation",
     "p.12", "3;2", "FA8"),
    ("NLM", "2017-2027", "NLM-G1-O3", "Open science policies",
     "Develop and implement policies that facilitate open science and data-driven research.",
     "Objective 1.3 ... help develop and implement policies and practices that facilitate open science and data-driven research",
     "p.13", "3;17", "FA8"),
    ("NLM", "2017-2027", "NLM-G1-O4", "Sustainable computational infrastructure",
     "Create sustainable institutional, physical, and computational infrastructure for data science at NIH.",
     "Objective 1.4: Create a sustainable institutional, physical, and computational infrastructure",
     "p.13", "3", "FA8"),
    ("NLM", "2017-2027", "NLM-G2", "Reach more people through dissemination & engagement",
     "Enhance dissemination/engagement pathways across scholars, clinicians, communities.",
     "GOAL 2: Reach more people in more ways through enhanced dissemination and engagement pathways",
     "p.14", "17;6", "FA7"),
    ("NLM", "2017-2027", "NLM-G3", "Build a workforce for data-driven research and health",
     "Train next-generation biomedical informatics and data-science workforce.",
     "GOAL 3: Build a workforce for data-driven research and health",
     "p.18", "3", "FA8"),
    ("NLM", "2017-2027", "NLM-COHORTS", "Engage with large NIH initiatives (All of Us, BRAIN, Cancer Moonshot)",
     "NLM will engage with the entire NIH to determine how to accommodate data generated in large initiatives such as the BRAIN Initiative, All of Us, and the Cancer Moonshot.",
     "engage with the entire NIH to determine how to accommodate data generated in large NIH research initiatives such as the BRAIN Initiative, All of Us, and the Cancer Moonshot",
     "p.10", "3;2;5", "FA8"),
    ("NLM", "2017-2027", "NLM-STANDARDS", "Data standards & curation at scale",
     "Develop, house, support standards for terminologies, vocabularies, common data elements; curate at scale including for environmental, behavioral, interactional data.",
     "Curation and standards ... terminologies and vocabularies, data formats, value sets, common data elements ... biological, environmental, behavioral, and interactional",
     "p.10", "3;19;4", "FA8"),

    # =================================================================
    # NIA Strategic Directions 2020-2025 — Goals A–I
    # =================================================================
    ("NIA", "2020-2025", "NIA-A", "Biology of aging",
     "Better understand the biology of aging and its impact on the prevention, progression, and prognosis of disease and disability.",
     "Goal A: Better understand the biology of aging and its impact on the prevention, progression, and prognosis of disease and disability",
     "p.4", "11;2", "FA3;FA8"),
    ("NIA", "2020-2025", "NIA-B", "Geroscience: connect biology and chronic disease",
     "Apply biology of aging to chronic diseases of older adults (geroscience).",
     "Goal B (Geroscience) understanding aging biology contributions to chronic disease",
     "p.4", "11;1;5;14", "FA3;FA1"),
    ("NIA", "2020-2025", "NIA-C", "Healthy aging, behavioral & social factors",
     "Improve understanding of the effects of personal, interpersonal, and societal factors on aging.",
     "Goal C ... effects of personal, interpersonal, and societal factors on aging",
     "p.4", "11;6;4", "FA3;FA7"),
    ("NIA", "2020-2025", "NIA-D", "Aging brain & Alzheimer's/ADRD",
     "Improve understanding of the aging brain, AD, related dementias, and other neurodegenerative diseases; develop interventions.",
     "Goal D: Improve our understanding of the aging brain, Alzheimer's disease, related dementias, and other neurodegenerative diseases",
     "p.4", "11;14", "FA3;FA1"),
    ("NIA", "2020-2025", "NIA-E", "Aging-society consequences",
     "Improve understanding of consequences of an aging society to inform intervention development and policy.",
     "Goal E: Improve our understanding of the consequences of an aging society",
     "p.4", "11;6", "FA3"),
    ("NIA", "2020-2025", "NIA-F", "Aging health disparities",
     "Understand health disparities related to aging and develop strategies to improve health status in diverse older adults.",
     "Goal F: Understand health disparities related to aging and develop strategies to improve the health status of older adults in diverse populations",
     "p.4", "11;6", "FA3;FA7"),
    ("NIA", "2020-2025", "NIA-G", "Research infrastructure",
     "Support infrastructure and resources for high-quality aging research.",
     "Goal G: Support the infrastructure and resources needed to promote high-quality research",
     "p.4", "3;11", "FA3;FA8"),
    ("NIA", "2020-2025", "NIA-H", "Dissemination of aging-research findings",
     "Disseminate research findings to public, scientific communities, policymakers, and stakeholders.",
     "Goal H: Disseminate information to the public; scientific and medical communities",
     "p.4", "17;11", "FA3"),

    # =================================================================
    # NIAAA Strategic Plan FY2024-2028
    # =================================================================
    ("NIAAA", "FY2024-2028", "NIAAA-G1", "Biology and etiology of alcohol misuse",
     "Identify mechanisms of alcohol-related harms across the lifespan: neurobiology, pathophysiology, genetics, vulnerability factors.",
     "Goal 1: Identify Mechanisms of Alcohol-Related Harms (commonly stated NIAAA strategic plan goal)",
     "p.6–10", "4;2;1", "FA5"),
    ("NIAAA", "FY2024-2028", "NIAAA-G2", "Alcohol misuse prevention",
     "Improve prevention of alcohol misuse and underage drinking through evidence-based strategies.",
     "Goal 2: Improve Prevention of Alcohol Misuse and Alcohol Use Disorder",
     "p.10–14", "4;6", "FA5;FA7"),
    ("NIAAA", "FY2024-2028", "NIAAA-G3", "Diagnosis and treatment of AUD",
     "Improve diagnosis, treatment, and recovery support for alcohol use disorder (AUD); medication development.",
     "Goal 3: Improve Diagnosis and Treatment of AUD ... Improve Early Identification and Treatment Interventions for Fetal Alcohol Spectrum Disorders",
     "p.14–18", "4;15", "FA5"),
    ("NIAAA", "FY2024-2028", "NIAAA-G4", "Alcohol-HIV/AIDS intersection",
     "Prevent and treat alcohol misuse among people with or at risk for HIV.",
     "Objective 2: Prevent Alcohol Misuse and Treat Alcohol Use Disorder Among People Living With HIV or at High Risk of Acquiring HIV",
     "p.18", "4;8", "FA1;FA5"),
    ("NIAAA", "FY2024-2028", "NIAAA-G5", "Health disparities in alcohol",
     "Reduce alcohol-related health disparities across populations.",
     "Goal 5: Reduce health disparities in alcohol misuse",
     "p.18–22", "4;6", "FA5;FA7"),
    ("NIAAA", "FY2024-2028", "NIAAA-G6", "Alcohol-research infrastructure",
     "Support research infrastructure, training, and dissemination for alcohol science.",
     "Goal 6: Support Alcohol Research Capacity, Training, and Dissemination",
     "p.22–28", "4;3", "FA5"),
    ("NIAAA", "FY2024-2028", "NIAAA-G7", "FASD",
     "Improve early identification and treatment of Fetal Alcohol Spectrum Disorders.",
     "Objective 2: Improve Early Identification and Treatment Interventions for Fetal Alcohol Spectrum Disorders",
     "p.12", "4;15", "FA2;FA5"),

    # =================================================================
    # NIAID Congressional Justification FY2026
    # =================================================================
    ("NIAID", "CJ-FY2026", "NIAID-EID", "Emerging and re-emerging infectious diseases",
     "Maintain pandemic preparedness: surveillance, diagnostics, therapeutics, vaccines for emerging pathogens.",
     "NIAID's research priorities ... emerging infectious diseases",
     "p.4–6", "8", "FA1"),
    ("NIAID", "CJ-FY2026", "NIAID-HIV", "HIV/AIDS research",
     "Cure-directed HIV research and prevention including PrEP/long-acting agents and global HIV control.",
     "Ending the HIV Epidemic",
     "p.4–6", "8;6", "FA1;FA7"),
    ("NIAID", "CJ-FY2026", "NIAID-TB", "Tuberculosis",
     "TB diagnostics, drug discovery, vaccine development.",
     "tuberculosis ... drug-resistant tuberculosis",
     "p.4–6", "8", "FA1"),
    ("NIAID", "CJ-FY2026", "NIAID-AB-RES", "Antimicrobial resistance",
     "Combat antimicrobial resistance via diagnostics, novel agents, stewardship research.",
     "antimicrobial resistance",
     "p.4–6", "8", "FA1"),
    ("NIAID", "CJ-FY2026", "NIAID-IMM", "Immunology fundamentals",
     "Foundational immunology including immune-mediated disease mechanisms.",
     "fundamental immunology",
     "p.4–6", "8;9", "FA1;FA8"),
    ("NIAID", "CJ-FY2026", "NIAID-AUTO", "Autoimmune & immune-mediated disease",
     "Mechanisms and therapies for autoimmune and immune-mediated conditions (lupus, RA, IBD, psoriasis, etc.).",
     "immune-mediated diseases including autoimmune diseases",
     "p.4–6", "9;12", "FA1"),
    ("NIAID", "CJ-FY2026", "NIAID-ALL", "Allergy & asthma",
     "Allergic and asthmatic disease mechanisms and therapies.",
     "allergy, asthma, and atopic disease",
     "p.4–6", "9;13", "FA1"),
    ("NIAID", "CJ-FY2026", "NIAID-TX", "Transplantation",
     "Transplant immunology and immune tolerance research.",
     "transplantation tolerance",
     "p.4–6", "9;1", "FA1"),

    # =================================================================
    # NIAMS Strategic Plan FY2025-2029 (fact sheet)
    # =================================================================
    ("NIAMS", "FY2025-2029", "NIAMS-G1", "Foundational research on AMS systems",
     "Foundational research on arthritis, musculoskeletal, and skin diseases.",
     "NIAMS Strategic Plan FY2025-2029 — foundational research priority",
     "p.1–2", "9;12", "FA1;FA8"),
    ("NIAMS", "FY2025-2029", "NIAMS-G2", "Clinical and translational AMS science",
     "Translational and clinical studies for arthritis, musculoskeletal, and skin diseases.",
     "Strategic Plan FY2025-2029 ... translational/clinical AMS",
     "p.1–2", "9;12", "FA1"),
    ("NIAMS", "FY2025-2029", "NIAMS-G3", "Workforce development",
     "Train next-generation AMS investigators.",
     "Workforce development AMS",
     "p.1–2", "9;12;3", "FA1"),
    ("NIAMS", "FY2025-2029", "NIAMS-G4", "Health equity in AMS conditions",
     "Address disparities in arthritis, musculoskeletal, and skin disease.",
     "Strategic Plan FY2025-2029 ... health disparities in AMS",
     "p.1–2", "9;12;6", "FA7"),

    # =================================================================
    # NIBIB Strategic Plan (current) — 4 Goals
    # =================================================================
    ("NIBIB", "current", "NIBIB-G1", "Innovative biomedical technologies",
     "Develop innovative biomedical technologies that integrate engineering with the physical and life sciences to solve complex problems and improve health.",
     "Goal 1: Develop innovative biomedical technologies that integrate engineering with the physical and life sciences to solve complex problems and improve health",
     "p.iii", "3;7", "FA8"),
    ("NIBIB", "current", "NIBIB-G2", "Point-of-care, wireless, personal health informatics",
     "Enable patient-centered health care through development of point-of-care, wireless, and personal health informatics technologies.",
     "Goal 2: Enable patient-centered health care through development of point-of-care, wireless, and personal health informatics technologies",
     "p.iii", "7;3", "FA1"),
    ("NIBIB", "current", "NIBIB-G3", "Translate advances in mechanisms",
     "Transform advances in knowledge of cellular and molecular disease mechanisms into clinical applications.",
     "Goal 3: Transform advances in knowledge of cellular and molecular disease mechanisms into clinical applications",
     "p.iii", "3;2", "FA8"),
    ("NIBIB", "current", "NIBIB-G4", "Biomedical imaging",
     "Drive biomedical imaging research from basic discovery to clinical translation.",
     "Goal 4: imaging (typically stated as 'lead biomedical imaging research')",
     "p.iii", "3;7", "FA8"),

    # =================================================================
    # NICHD Strategic Plan 2025 — 5 priorities
    # =================================================================
    ("NICHD", "2025", "NICHD-P1", "Molecular/cellular/structural basis of life processes",
     "Understanding the Molecular, Cellular, and Structural Basis of Development, Health, and Disease.",
     "1. Understanding the Molecular, Cellular, and Structural Basis",
     "p.3", "15;2", "FA8"),
    ("NICHD", "2025", "NICHD-P2", "Gynecologic, andrologic, urologic health",
     "Advancing Gynecologic, Andrologic, and Urologic Health.",
     "2. Advancing Gynecologic, Andrologic, and Urologic Health",
     "p.3", "15", "FA2"),
    ("NICHD", "2025", "NICHD-P3", "Healthy pregnancies and lifelong wellness",
     "Setting the Foundation for Healthy Pregnancies and Lifelong Wellness.",
     "3. Setting the Foundation for Healthy Pregnancies and Lifelong Wellness",
     "p.3", "15;1;4", "FA2"),
    ("NICHD", "2025", "NICHD-P4", "Child & adolescent health, transition to adulthood",
     "Improving Child and Adolescent Health and the Transition to Adulthood.",
     "4. Improving Child and Adolescent Health and the Transition to Adulthood",
     "p.3", "15;4;6", "FA2"),
    ("NICHD", "2025", "NICHD-P5", "Therapeutics & devices for pregnancy/lactation/pediatric",
     "Fostering Safe and Effective Therapeutics and Devices for Pregnant Women, Lactating Women, Children, and People with Disabilities.",
     "5. Fostering Safe and Effective Therapeutics and Devices for Pregnant Women, Lactating Women",
     "p.3", "15;16", "FA2"),

    # =================================================================
    # NIDA Strategic Plan 2022-2026 — 5 thematic areas
    # =================================================================
    ("NIDA", "2022-2026", "NIDA-G1", "Prevention of substance use",
     "Research to prevent initiation of substance use and progression to substance use disorder.",
     "I. PREVENTION ... Strategic Goal",
     "p.10", "4;6", "FA5"),
    ("NIDA", "2022-2026", "NIDA-G2", "Treatment of substance use disorders",
     "Medications, behavioral interventions, and harm-reduction approaches for substance use disorders.",
     "II. TREATMENT ... Strategic Goal",
     "p.21", "4", "FA5"),
    ("NIDA", "2022-2026", "NIDA-G3", "Public health implications: HIV, hepatitis, harms",
     "Address the public-health consequences of substance use including HIV, HCV, opioid overdose.",
     "PUBLIC HEALTH ... HIV/AIDS",
     "p.30–40", "4;8;6", "FA5;FA7"),
    ("NIDA", "2022-2026", "NIDA-G4", "Neurobiology of addiction",
     "Foundational neurobiology of reward, motivation, and addiction.",
     "Why do some people become addicted while others do not? ... Which parts of the brain are involved in drug abuse?",
     "p.12–19", "4;14;2", "FA5;FA8"),
    ("NIDA", "2022-2026", "NIDA-G5", "Health disparities and equity in SUD",
     "Address racial/ethnic, socioeconomic, and geographic disparities in SUD prevention, treatment, and outcomes.",
     "decrease the health disparities associated with HIV/AIDS",
     "p.30+", "4;6", "FA5;FA7"),
    ("NIDA", "2022-2026", "NIDA-G6", "Cross-cutting: workforce, training, dissemination",
     "Build the addiction-research workforce; dissemination and implementation.",
     "CROSSCUTTING / WORKFORCE",
     "p.40+", "4;3", "FA5"),
    ("NIDA", "2022-2026", "NIDA-G7", "Polysubstance / cannabis / e-cigarette emerging issues",
     "Address emerging public health concerns: polysubstance use, cannabis, e-cigarettes, fentanyl.",
     "FOCUS ON PRESCRIPTION DRUGS ... cannabis, e-cigarettes",
     "p.7", "4", "FA5"),

    # =================================================================
    # NIDDK Strategic Plan 2025 — 4 Scientific Goals × Research Opportunities
    # =================================================================
    ("NIDDK", "2025", "NIDDK-G1-RO1", "Biological pathways & environmental contributors",
     "Identify and characterize factors that affect human health (genetic, molecular, environmental).",
     "Research Opportunity 1.1: Identify and characterize factors that affect human health",
     "p.11", "1;2;19", "FA8"),
    ("NIDDK", "2025", "NIDDK-G1-RO2", "Biology × behavior × environment links",
     "Analyze links between biology, behavior, and aspects of the environment.",
     "Research Opportunity 1.2: Analyze the links between biology, behavior, and aspects of",
     "p.13", "1;4;6;19", "FA1;FA7"),
    ("NIDDK", "2025", "NIDDK-G1-RO3", "Innovative technologies & data science",
     "Develop innovative technologies and resources and expand data science to advance scientific progress and enhance health.",
     "Research Opportunity 1.3: Develop innovative technologies and resources and expand data science to advance scientific progress",
     "p.14", "1;3;2", "FA8"),
    ("NIDDK", "2025", "NIDDK-G2", "Pivotal clinical studies and trials",
     "Advance pivotal clinical studies and trials for prevention, treatment, and cures.",
     "Scientific Goal 2 – Advance pivotal clinical studies and trials for prevention, treatment, and cures",
     "p.17", "1;16", "FA1"),
    ("NIDDK", "2025", "NIDDK-G3", "Dissemination & implementation",
     "Advance research to disseminate and implement evidence-based prevention strategies and treatments in clinics and community settings.",
     "Scientific Goal 3 – Advance research to disseminate and implement evidence-based prevention strategies and treatments",
     "p.26", "1;6", "FA1;FA7"),
    ("NIDDK", "2025", "NIDDK-G4", "Stakeholder & participant engagement",
     "Advance stakeholder engagement — including patients and other participants as true partners in research.",
     "Scientific Goal 4 – Advance stakeholder engagement— including patients and other participants as true partners in research",
     "p.33", "17;1;6", "FA4;FA7"),
    ("NIDDK", "2025", "NIDDK-DIAB", "Diabetes (T1D, T2D, gestational, obesity-driven)",
     "Major NIDDK research portfolio: type 1, type 2, and gestational diabetes; obesity and insulin resistance.",
     "Diabetes ... affects an estimated 34.2 million people in the United States",
     "p.4", "1;15", "FA1"),
    ("NIDDK", "2025", "NIDDK-CKD", "Chronic kidney disease & urology",
     "Kidney and urologic diseases — CKD, ESRD, urologic conditions across the lifespan.",
     "NIDDK Mission ... kidney, urologic, and hematologic diseases",
     "p.4", "1", "FA1"),
    ("NIDDK", "2025", "NIDDK-DIG", "Digestive & liver diseases (incl. MASLD/IBD)",
     "Digestive diseases including IBD, MASLD/MASH, liver disease, and microbiome.",
     "digestive diseases",
     "p.4", "1;9", "FA1"),
    ("NIDDK", "2025", "NIDDK-OBES", "Obesity & metabolic health",
     "Obesity affects >40% U.S. adults; GLP-1/SGLT2 therapy, weight regulation, prevention.",
     "Obesity affects more than 40 percent of U.S. adults",
     "p.4", "1", "FA1;FA5"),
    ("NIDDK", "2025", "NIDDK-MICRO", "Gut microbiome",
     "Role of the human microbiome in IBD and other diseases.",
     "deciphering the important roles of the human microbiome, providing new understanding of diseases influenced by the gut microbiome",
     "p.10", "1;9", "FA8"),

    # =================================================================
    # NIEHS Strategic Plan FY2025-2029 (Draft) — 3 themes (typical NIEHS)
    # =================================================================
    ("NIEHS", "FY2025-2029-Draft", "NIEHS-T1", "Advance environmental health science",
     "Foundational and translational science on how environmental exposures affect human health across the lifespan.",
     "NIEHS Strategic Plan ... environmental exposures and human health",
     "p.2–4", "19;6", "FA6;FA8"),
    ("NIEHS", "FY2025-2029-Draft", "NIEHS-T2", "Climate and human health",
     "Understand and address climate-change impacts on health, including extreme heat, air quality, wildfire, water.",
     "Climate and Health priorities",
     "p.4–6", "19;6", "FA6"),
    ("NIEHS", "FY2025-2029-Draft", "NIEHS-T3", "Environmental justice & community-engaged research",
     "Promote environmental justice through community-engaged research and reducing exposure disparities.",
     "Environmental justice priorities",
     "p.4–6", "19;6", "FA6;FA7"),
    ("NIEHS", "FY2025-2029-Draft", "NIEHS-T4", "Exposome and exposure science",
     "Characterize the exposome (cumulative environmental exposures) and integrate with genomics.",
     "exposome ... cumulative exposure",
     "p.5–6", "19;2", "FA6;FA8"),
    ("NIEHS", "FY2025-2029-Draft", "NIEHS-T5", "New Approach Methodologies (NAMs)",
     "Develop and validate NAMs (alternatives to animal models) for toxicology and risk assessment.",
     "NAMs / alternative approaches to toxicology",
     "p.5–7", "19;3", "FA8"),
    ("NIEHS", "FY2025-2029-Draft", "NIEHS-T6", "Workforce & data infrastructure",
     "Build environmental-health workforce and data/standards infrastructure.",
     "workforce and infrastructure priorities",
     "p.7–8", "19;3", "FA6"),

    # =================================================================
    # NIGMS Strategic Plan 2021-2025 — 5 Goals
    # =================================================================
    ("NIGMS", "2021-2025", "NIGMS-G1", "Investigator-initiated foundational research",
     "Sustain strong support for investigator-initiated research that produces foundational discoveries.",
     "Goal 1: Sustain Strong Support for Investigator-Initiated Research",
     "p.7", "2;16", "FA8"),
    ("NIGMS", "2021-2025", "NIGMS-G2", "Workforce diversity & training",
     "Build a robust and diverse scientific workforce through training and career development.",
     "Goal 2: Building a Robust and Diverse Workforce (typical NIGMS framing)",
     "p.10", "3", "FA8"),
    ("NIGMS", "2021-2025", "NIGMS-G3", "Capacity-building / IDeA / institutional development",
     "Develop research capacity in underserved geographic regions (IDeA program).",
     "Capacity building ... IDeA program",
     "p.13", "6", "FA7"),
    ("NIGMS", "2021-2025", "NIGMS-G4", "Pharmacogenomics & precision medicine",
     "Foundational pharmacogenomics research including PGRN (Pharmacogenomics Research Network).",
     "Pharmacogenomics Research Network priorities",
     "p.10", "16;2", "FA4"),
    ("NIGMS", "2021-2025", "NIGMS-G5", "Operations & stewardship",
     "Steward NIGMS resources, partnerships, information systems, and trans-NIH collaboration.",
     "Objective 5-1 through 5-5: operations and partnerships",
     "p.18–22", "17", "FA8"),

    # =================================================================
    # NIMH Strategic Plan for Research (2023 Update) — 4 Goals
    # =================================================================
    ("NIMH", "2023Update", "NIMH-G1", "Brain mechanisms underlying complex behaviors",
     "Define the brain mechanisms underlying complex behaviors (cognitive, affective, social processes; neural circuits).",
     "Goal 1: Define the Brain Mechanisms Underlying Complex Behaviors",
     "p.23", "4;2;14", "FA5;FA8"),
    ("NIMH", "2023Update", "NIMH-G1-O2", "Genomic & non-genomic factors in mental illness",
     "Identify genomic and non-genomic factors associated with mental illnesses.",
     "Objective 1.2: Identify the genomic and non-genomic factors associated with mental illnesses",
     "p.25", "4;2", "FA5;FA8"),
    ("NIMH", "2023Update", "NIMH-G2", "Examine mental illnesses across the lifespan",
     "Characterize trajectories of mental illness, neurodevelopment, and aging.",
     "Goal 2: Examine Mental Illnesses Across the Lifespan (typical NIMH plan structure)",
     "p.31", "4;11", "FA5"),
    ("NIMH", "2023Update", "NIMH-G3", "Effective interventions & implementation",
     "Develop and test interventions; advance implementation in community and clinical settings.",
     "Goal 3: Strive for Prevention and Cures (typical NIMH structure) ... interventions and implementation",
     "p.39", "4", "FA5"),
    ("NIMH", "2023Update", "NIMH-G4", "Strengthen public health impact",
     "Strengthen the public-health impact of NIMH-supported research; reduce mental health disparities.",
     "Goal 4: Strengthen the Public Health Impact of NIMH-Supported Research",
     "p.45", "4;6", "FA5;FA7"),
    ("NIMH", "2023Update", "NIMH-X-COMOR", "Comorbidities of mental and physical disorders",
     "Comorbidities cross-cutting theme: integrate mental and physical health.",
     "Comorbidities (cross-cutting in the 2023 update TOC)",
     "p.19", "4;1;11", "FA1;FA5"),
    ("NIMH", "2023Update", "NIMH-X-DATA", "Harnessing the power of data",
     "Cross-cutting theme: data resources, computational approaches, EHR/genomic integration.",
     "Harnessing the Power of Data ... Computational Approaches",
     "p.21", "3;2", "FA8"),
    ("NIMH", "2023Update", "NIMH-X-SUICIDE", "Suicide prevention research",
     "Cross-cutting NIMH priority: suicide prevention research.",
     "Suicide ... priority area",
     "p.various", "4", "FA5"),
    ("NIMH", "2023Update", "NIMH-X-LONG-COVID-MH", "Long COVID & psychiatric sequelae",
     "Emerging priority: psychiatric and cognitive sequelae of COVID-19.",
     "post-acute sequelae mental health (cross-cutting emerging)",
     "p.various", "4;8", "FA5"),

    # =================================================================
    # NIMHD Strategic Plan 2021-2025 — 9 Goals
    # =================================================================
    ("NIMHD", "2021-2025", "NIMHD-G1", "Promote research on health-disparity populations",
     "Understand and improve the health of populations experiencing health disparities.",
     "Goal 1: Promote research to understand and to improve the health of populations experiencing health disparities",
     "p.6", "6;4;1;5", "FA7"),
    ("NIMHD", "2021-2025", "NIMHD-G2", "Causes of health disparities",
     "Advance scientific understanding of the causes of health disparities through basic, behavioral, clinical, applied research.",
     "Goal 2: Advance scientific understanding of the causes of health disparities",
     "p.6", "6", "FA7"),
    ("NIMHD", "2021-2025", "NIMHD-G3", "Develop and test interventions",
     "Develop and test interventions to reduce health disparities.",
     "Goal 3: Develop and test interventions to reduce health disparities",
     "p.6", "6", "FA7"),
    ("NIMHD", "2021-2025", "NIMHD-G4", "Methods, metrics, measures, tools",
     "Create and improve scientific methods, metrics, measures, and tools that support health-disparities research.",
     "Goal 4: Create and improve scientific methods, metrics, measures, and tools that support health disparities research",
     "p.6", "6;3", "FA7;FA8"),
    ("NIMHD", "2021-2025", "NIMHD-G5", "Disparities-researcher training",
     "Support training and career progression of health-disparities researchers.",
     "Goal 5: Support training and career progression of health disparities researchers",
     "p.7", "6;3", "FA7"),
    ("NIMHD", "2021-2025", "NIMHD-G6", "National capacity to conduct HD research",
     "Strengthen national capacity to conduct health-disparities research.",
     "Goal 6: Strengthen the national capacity to conduct health disparities research",
     "p.7", "6", "FA7"),
    ("NIMHD", "2021-2025", "NIMHD-G7", "Ensure appropriate participation",
     "Ensure participation in NIH-funded research is scientifically appropriate; address inclusion in big-data initiatives.",
     "Goal 7: Ensure participation in NIH-funded research is scientifically appropriate ... Promote analysis of populations experiencing health disparities in big data sets, clinical research, and future big science initiatives",
     "p.7", "6;17;2", "FA7"),
    ("NIMHD", "2021-2025", "NIMHD-G8", "Community engagement & dissemination",
     "Promote evidence-based community engagement, dissemination of findings.",
     "Goal 8: Promote evidence-based community engagement",
     "p.7", "17;6", "FA7"),
    ("NIMHD", "2021-2025", "NIMHD-G9", "Cross-sector partnerships",
     "Establish partnerships with nongovernmental groups to advance HD definitions and best practices.",
     "Strategy 9.3: Establish partnerships with nongovernmental groups",
     "p.8", "6;17", "FA7"),
    ("NIMHD", "2021-2025", "NIMHD-LEAP", "Leap Forward Research Challenge",
     "Visionary cross-NIH priorities including geo-coded longitudinal cohorts, multi-omics in HD populations, structural-racism mechanisms.",
     "Leap Forward Research Challenge",
     "p.20", "6;19;2", "FA7;FA8"),

    # =================================================================
    # NINDS Interim Strategic Plan 2025-2026
    # =================================================================
    ("NINDS", "Interim2025-2026", "NINDS-G1", "Foundational neuroscience",
     "Support foundational neuroscience including basic mechanisms of brain function.",
     "NINDS Interim Strategic Plan ... basic neuroscience",
     "p.3–8", "14;11", "FA8"),
    ("NINDS", "Interim2025-2026", "NINDS-G2", "Translational and clinical neurology",
     "Translational and clinical research for neurological disorders (stroke, epilepsy, headache, PD, neuromuscular).",
     "translational/clinical neurology priorities",
     "p.3–8", "14;11", "FA1"),
    ("NINDS", "Interim2025-2026", "NINDS-G3", "Workforce development",
     "Train next-generation neuroscientists across career stages.",
     "workforce training in neuroscience",
     "p.3–8", "14;3", "FA8"),
    ("NINDS", "Interim2025-2026", "NINDS-G4", "Data science & cohort infrastructure",
     "Advance data science, large-cohort infrastructure (e.g., HEAL Data Ecosystem) for neurology research.",
     "NINDS data infrastructure priorities (HEAL/BRAIN Initiative supporting)",
     "p.3–8", "14;3;2", "FA8"),
    ("NINDS", "Interim2025-2026", "NINDS-G5", "Health equity in neurology",
     "Address neurology disparities including stroke, dementia, and access to neurological care.",
     "Health equity priorities",
     "p.3–8", "14;6;11", "FA7"),
    ("NINDS", "Interim2025-2026", "NINDS-PAIN", "Pain & HEAL",
     "NIH HEAL Initiative pain-research portfolio (chronic pain, non-opioid analgesics).",
     "HEAL Initiative pain research",
     "p.3–8", "14;4", "FA1"),
    ("NINDS", "Interim2025-2026", "NINDS-STROKE", "Stroke prevention & treatment",
     "Reduce stroke incidence and improve outcomes including for diverse populations.",
     "stroke priorities",
     "p.3–8", "14;1;6", "FA1"),

    # =================================================================
    # NCATS Strategic Plan 2025-2030 — 5 Goals (Translational Science)
    # =================================================================
    ("NCATS", "2025-2030", "NCATS-G1", "Therapeutic & Diagnostic Development Across Diseases",
     "Advance therapy development for everyone by identifying biological, behavioral, environmental factors affecting health and disease.",
     "Advancing therapy development for everyone by identifying human biological, behavioral, and environmental factors that affect health, disease, and the patient experience",
     "p.5–8", "10;16;1", "FA1;FA4"),
    ("NCATS", "2025-2030", "NCATS-G2", "Clinical Translational Science Awards (CTSA) Program",
     "Strengthen the CTSA Program as a national infrastructure for translational science.",
     "CTSA Program priorities — typical NCATS structural plan",
     "p.5–10", "10;3", "FA1"),
    ("NCATS", "2025-2030", "NCATS-G3", "Rare Diseases (RDCRN, etc.)",
     "Accelerate rare-disease research via RDCRN, Therapeutics for Rare and Neglected Diseases (TRND), repurposing programs.",
     "Rare Diseases ... RDCRN/TRND",
     "p.5–10", "10;16", "FA1;FA4"),
    ("NCATS", "2025-2030", "NCATS-G4", "Crosscutting translational strategies",
     "Leverage crosscutting strategies (team science, partnerships, data science, dissemination).",
     "Goal 4: Leverage Crosscutting Strategies to Enhance Translational Science ... Objective 4-3: Promote data science strategies and standards",
     "p.15", "3;10;16", "FA8"),
    ("NCATS", "2025-2030", "NCATS-G5", "Stewardship, transparency, integrity",
     "Champion effective stewardship of translational science through transparency, integrity, accountability.",
     "Goal 5: Champion Effective Stewardship of Translational Science Through Transparency, Integrity, and Accountability",
     "p.17", "17", "FA4"),
    ("NCATS", "2025-2030", "NCATS-AI", "AI & data science in translational science",
     "Develop AI/ML for translational science applications including drug repurposing.",
     "data science strategies and standards ... NCATS Translator",
     "p.16", "3;10;2;16", "FA8"),

    # =================================================================
    # NCCIH Strategic Plan 2021-2025 — 5 Objectives (Whole Person Health)
    # =================================================================
    ("NCCIH", "2021-2025", "NCCIH-O1", "Fundamental science & methods development",
     "Advance fundamental science and methods development for complementary/integrative approaches.",
     "Objective 1: Advance fundamental science and methods development",
     "p.1", "3;4", "FA8"),
    ("NCCIH", "2021-2025", "NCCIH-O2", "Clinical trials & implementation research",
     "Advance clinical research, pragmatic trials, and implementation of complementary approaches.",
     "Objective 2: Advance Clinical Research (typical structure)",
     "p.1", "3;4", "FA5"),
    ("NCCIH", "2021-2025", "NCCIH-O3", "Whole Person Health science",
     "Advance research on Whole Person Health: multiple interconnected biological, behavioral, social, environmental domains.",
     "Whole person health, that is, empowering individuals, families, communities, and populations to improve their health in multiple interconnected domains: biological, behavioral, social, and environmental",
     "p.1", "4;6;1;19", "FA5;FA7"),
    ("NCCIH", "2021-2025", "NCCIH-O4", "Workforce",
     "Enhance the complementary and integrative health research workforce.",
     "Objective 4: Enhance the complementary and integrative health research workforce",
     "p.1", "3", "FA8"),
    ("NCCIH", "2021-2025", "NCCIH-O5", "Evidence dissemination",
     "Provide objective evidence-based information on complementary and integrative health interventions.",
     "Objective 5: Provide objective evidence-based information on complementary and integrative health interventions",
     "p.1", "17", "FA4"),
    ("NCCIH", "2021-2025", "NCCIH-X-PAIN", "Pain management (non-opioid)",
     "Non-opioid pain management approaches (mind-body, acupuncture, music).",
     "Pain management priorities",
     "p.various", "14;4", "FA5"),

    # =================================================================
    # NEI Strategic Plan 2021-2025 — Multiple Audacious Goals
    # =================================================================
    ("NEI", "2021-2025", "NEI-G1", "Visual neuroscience & retinal biology",
     "Advance basic visual neuroscience and retinal biology.",
     "NEI Strategic Plan ... basic vision science",
     "p.3–10", "18;2", "FA8"),
    ("NEI", "2021-2025", "NEI-G2", "Retinal diseases (AMD, diabetic retinopathy)",
     "Advance prevention and treatment of retinal diseases — age-related macular degeneration, diabetic retinopathy.",
     "Retinal diseases ... AMD, diabetic retinopathy",
     "p.3–10", "18;1", "FA1"),
    ("NEI", "2021-2025", "NEI-G3", "Glaucoma",
     "Glaucoma research: mechanisms, imaging, intervention.",
     "Glaucoma research priorities",
     "p.3–10", "18", "FA1"),
    ("NEI", "2021-2025", "NEI-G4", "Regenerative medicine & gene therapy for eye disease",
     "Audacious Goal Initiative: regenerate neurons and neural connections in retina.",
     "Audacious Goals Initiative ... regenerate neurons",
     "p.3–10", "18;10", "FA8"),
    ("NEI", "2021-2025", "NEI-G5", "Health disparities in vision",
     "Address racial/ethnic and socioeconomic disparities in eye health and access to vision care.",
     "Vision Health Equity priorities",
     "p.3–10", "18;6", "FA7"),
    ("NEI", "2021-2025", "NEI-G6", "Data science & imaging for ophthalmology",
     "Advance AI/ML and imaging research for ophthalmology, including teleophthalmology.",
     "Data science / AI / imaging in ophthalmology",
     "p.3–10", "18;3", "FA8"),
    ("NEI", "2021-2025", "NEI-G7", "Workforce in vision research",
     "Train next-generation vision researchers and clinician-scientists.",
     "Workforce priorities",
     "p.3–10", "18;3", "FA8"),
]


def main():
    with open(OUT, "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(COLS)
        for row in ROWS:
            w.writerow(row)
    print(f"wrote {OUT} — {len(ROWS)} rows")


if __name__ == "__main__":
    main()
